server:
  port: 9999
spring:
  datasource:
    druid:
      url: jdbc:mysql://mysql:13306/llwell?useUnicode=true&characterEncoding=utf8
      username: root
      password: ENC(rbl6larX3FdtJm/uZiS1sdJk3N1ttINm)
      filters: stat,slf4j
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  redis: 
    database: 0
    host: redis-api
    port: 6379
    password: 
    timeout: 0
    pool: 
      max-active: 10
      max-wait: -1
      max-idle: 10
      min-idle: 0
    expireTime: 7200
  mail:  
    host: smtp.mxhichina.com  
    username: app@llwell.net     
    password: ENC(cYOumtVNlPAct4guNSVMZ+NYyNP+X+CI) 
    port: 465  
    default-encoding: UTF-8  
    protocol: smtp  
    properties:  
      mail:  
        smtp:  
          auth: true 
          ssl: true 
          starttls:  
            enable: true  
            required: true
          timeout: 10000
logging: 
  config: classpath:log4j2-prod.xml
